config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :bookings, :clubs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :club

  scope :on_date, -> (date) { where("DATE(tee_time) = ?", date) }

  def pretty_time
    tee_time.strftime("%b %e, %l:%M %p")
  end

end

app/models/club.rb
class Club < ApplicationRecord
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    clubs_path
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
  end

  def create
    @booking = Booking.create!(booking_params)
    flash[:create] = "You have booked a tee time for #{@booking.pretty_time}" 
    redirect_to club_path(@booking.club, date: booking_params[:tee_time])
  end

  def destroy
    @booking = Booking.find(params[:id])

    club = @booking.club
    date = @booking.tee_time
    flash[:destroy] = "You have cancelled your booking for #{@booking.pretty_time}"

    @booking.destroy

    redirect_to club_path(club, date: date)
  end

  def booking_params
    params.require(:booking).permit!
  end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  def index
    @clubs = Club.all
  end

  def show
    @club = Club.find(params[:id])
    @date = DateTime.parse(params[:date])
    @user = current_user
    start_time = @date.change({ hour: 9, min: 0, sec: 0})

    @time_slots = (0..23).map do |slot|
      (start_time + (slot * 20).minutes)
    end

    @club_bookings = Booking.where(club_id: @club).on_date(@date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def pretty_time(time)
    time.strftime("%b %e, %l:%M %p")
  end

end

app/views/bookings/index.html.haml
.container
  %h1 Show current_user bookings

app/views/clubs/index.html.haml
.container
  %h1 Clubs

  %table.table.table-bordered
    %thead
      %th Club
    %tbody
      - @clubs.each_with_index do |club, index|
        %tr
          %td
            %form.navbar-form.pull-right{ action: club_path(club), method: "GET", name: "datepicker#{index}"  }
              %label
                = club.name
              .form-group
                .input-group.date
                  %input.form-control{:type => "text", name: "date", id: "datepicker#{index}"}
                  %span.input-group-addon
                    %span.glyphicon.glyphicon-calendar

              :javascript
                $(document).ready(function(){

                  flatpickr('#datepicker#{index}', {  
                    onChange: function() {
                      $("form[name=datepicker#{index}]").submit()
                    }
                  })

                  //format: "YYYY/MM/DD"

                });
             
      

app/views/clubs/show.html.haml
.container
  .row
    .col-md-2
      %img{src: image_url("golf-tee.jpeg"), style: "width: 100%"}
    .col-md-10
      %h1= @club.name

  %br
  - if flash[:create]
    .alert.alert-success= flash[:create]
  - if flash[:destroy]
    .alert.alert-danger= flash[:destroy]

  %table.table.table-bordered
    %thead
      %tr
        %th Time Slot
        %th Booking
    %tbody
      - @time_slots.each do |time|
        %tr
          %td= pretty_time(time)
          %td
            - current_booking = @club_bookings.find_by(tee_time: time, club_id: @club.id)
            - if current_booking
              - if current_booking.user_id == @user.id
                = link_to "Cancel Booking", booking_path(current_booking), method: :delete, class: "btn btn-danger"
              - else
                %p Booked by other Golfer
            - else
              = simple_form_for(Booking.new) do |f|
                = f.hidden_field :user_id, value: @user.id
                = f.hidden_field :club_id, value: @club.id
                = f.hidden_field :tee_time, value: time
                = f.submit "Book time", class: "btn btn-info"



 

app/views/home/index.html.haml
.container
  .row
    .col-md-2
      %img{src: image_url("golf-tee.jpeg"), style: "width: 100%"}
    .col-md-10
      %h1= @club.name

  %br
  - if flash[:create]
    .alert.alert-warning= flash[:create]
  - if flash[:destroy]
    .alert.alert-danger= flash[:destroy]

  %table.table.table-bordered
    %thead
      %tr
        %th Time Slot
        %th Booking
    %tbody
      - @time_slots.each do |time|
        %tr
          %td= pretty_time(time)
          %td
            - current_booking = @club_bookings.find_by(time: time, club_id: @club.id)
            - if current_booking
              - if current_booking.user_id == @user.id
                = link_to "Cancel Booking", booking_path(current_booking), method: :delete, class: "btn btn-danger"
              - else
                %p Booked by other Golfer
            - else
              = simple_form_for(Booking.new) do |f|
                = f.hidden_field :user_id, value: @user.id
                = f.hidden_field :club_id, value: @club.id
                = f.hidden_field :date, value: @current_date
                = f.hidden_field :time, value: time
                = f.submit "Book time", class: "btn btn-info"



 

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TeeTime
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path }
            Tee Time

        .collapse.navbar-collapse.navbar-ex1-collapse
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                = link_to "Log out", destroy_user_session_path, :method => :delete
            - else
              %li
                = link_to "Log in", new_user_session_path



    = yield